name: CI

on: [push, pull_request]

jobs:
  build:
    name: Rusty build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta, stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo build --release
